version: '2'
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: postgres_test
    volumes:                
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: